### ISSUE TITLE
Questions about the client

### ISSUE THREAD

**Issue by EPuncker** [omarcopires/server#15]
Cara muito obrigado mas muito obrigado mesmo por esse server, vc não faz ideia do quanto eu e o @guiismiti estavamos tentando fazer o TFS funfar com o suporte ao client 11/12 pra não ter q depender de outros códigos, eu até agora não to acreditando que consegui logar nesse server com client 12 sem nenhum erro, só criei esse issue mesmo pra agradecer e pra saber se tem o link do client 12.30+?

esse é meu novo engine principal agora

**Comment by omarcopires** [comment]
@EPuncker eu que tenho que te agradecer por todos commits no repositório oficial da otland.
Bem, eu estou utilizando o ultimo client da CipSoft, as únicas coisa que eu fiz foi mudar o ip de login é claro, e também alterar a chave RSA.
Sobre o login.php o @jlcvp disponibilizou o suporte compatível para minha versão do gesior. Você podene encontrar neste link: https://github.com/omarcopires/gesior
